"""
Django settings for BaseProject.Core.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
import sys
import json
import inspect
import environ
from pathlib import Path

from django.utils.translation import gettext_lazy as _
from .components.drf import DRFConfig
from BaseProject.core.utilities.load_kit_settings import file_name, load_kit_config, validate_components


class BaseSettings:
    """ Community base settings, don't use this directly. """

    def __init__(self, *args, **kwargs):
        # Main Path
        self.BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent

        # load components
        kit = load_kit_config(self.BASE_DIR / f'.config_project/{file_name}')
        validate_components(kit['components'])
        self.DJANGO_SECRETS_BACKEND = kit['secrets_backend']
        self.DJANGO_STORAGE_BACKEND = kit['storage_backend']

        # load environments from Docker Compose
        self.env = environ.Env() # instance the environ object and read from user environment variables.
        # secrets
        if self.DJANGO_SECRETS_BACKEND == 'aws':
            from .loaders.aws import SecretsConfig
            secrets = SecretsConfig({
                "AWS_REGION_NAME": self.env.str("AWS_REGION_NAME"),
                "AWS_SECRET_NAME": self.env.str("AWS_SECRET_NAME"),
                "AWS_ACCESS_KEY_ID": self.env.str("AWS_ACCESS_KEY_ID"),
                "AWS_SECRET_ACCESS_KEY": self.env.str("AWS_SECRET_ACCESS_KEY")
            })
            secrets.load_env()

        self.INSTALLED_APPS = [
            # django apps
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'django.contrib.humanize',
            'django.contrib.sites',
            # Project apps
            'BaseProject.apps.admin_portal',
            'BaseProject.apps.core_user'
        ]

        # storage
        if self.DJANGO_STORAGE_BACKEND == 'aws':
            from .components.s3 import S3Config
            self._apply(S3Config, {})
        else:
            self.STATIC_URL = self.env.str('STATIC_URL', '/static/')
            self.MEDIA_URL = self.env.str('MEDIA_URL', '/media/')

        # drf
        self._apply(DRFConfig, kit['components'].get('drf', {}))

        # default values for media and static
        self.AUTH_USER_MODEL = self.env.str('AUTH_USER_MODEL', 'core_user.User')
        self.SECRET_KEY = self.env.str('SECRET_KEY')
        self.SITE_ID = self.env.int('SITE_ID', 1)
        self.ROOT_URLCONF = 'BaseProject.core.urls'
        self.STATIC_ROOT = self.BASE_DIR / '.static'
        self.MEDIA_ROOT = self.BASE_DIR / '.media'

        # Debug settings
        self.DEBUG = self.env.bool('DEBUG')
        self.DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
        self.WSGI_APPLICATION = 'BaseProject.core.wsgi.application'

        # Admin Vars
        self.ADMIN_SITE_HEADER = self.env.str('ADMIN_SITE_HEADER', "BaseProject")
        self.ADMIN_SITE_TITLE = self.env.str('ADMIN_SITE_TITLE', "Base Project")
        self.ADMIN_SITE_INDEX_TITLE = self.env.str('ADMIN_SITE_INDEX_TITLE', "Base Project Index")
        self.SITE_URL = '/'

        # settings EMAIL
        for _key, _val in self.env.email_url().items():
            setattr(self, _key, _val)

        self.FIXTURE_DIRS = [self.BASE_DIR / '.config_project/DB_Fixtures']
        self.MIDDLEWARE = [
            'django.middleware.security.SecurityMiddleware',
            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.locale.LocaleMiddleware',
            'django.middleware.common.CommonMiddleware',
            'django.middleware.common.BrokenLinkEmailsMiddleware',
            'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',
            'django.contrib.messages.middleware.MessageMiddleware',
            'django.middleware.clickjacking.XFrameOptionsMiddleware',
            # 'allauth.account.middleware.AccountMiddleware',
            "django_htmx.middleware.HtmxMiddleware",
            # 'corsheaders.middleware.CorsMiddleware',
        ]

        self.STATICFILES_DIRS = [
            self.BASE_DIR / 'BaseProject/static',
        ]

        self.STATICFILES_FINDERS = [
            'django.contrib.staticfiles.finders.FileSystemFinder',
            'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        ]

        self.TEMPLATE_ROOT = self.BASE_DIR / 'BaseProject/templates'

        self.TEMPLATES = [
            {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [self.TEMPLATE_ROOT],
                'OPTIONS': {
                    'debug': self.DEBUG,
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                    ],
                    'loaders': [
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ],
                },
            },
        ]

        self.AUTHENTICATION_BACKENDS = [
            'django.contrib.auth.backends.ModelBackend',
            # 'allauth.account.auth_backends.AuthenticationBackend',
        ]

        self.LOGIN_URL = 'account_login'
        self.ACCOUNT_LOGOUT_REDIRECT_URL = 'account_login'

        self.TIME_ZONE = self.env.str('TIME_ZONE','America/Mexico_City')
        self.USE_TZ = self.env.bool('USE_TZ', True)
        self.LANGUAGE_CODE = self.env.str('LANGUAGE_CODE', 'es-mx')
        self.USE_I18N = self.env.bool('USE_I18N', True)
        self.USE_L10N = self.env.bool('USE_L10N', True)
        self.LOCALE_PATHS = [
            self.BASE_DIR / 'BaseProject/locale',
        ]

        self.LANGUAGES = [
            ('en-us', 'Inglés'),
            ('es-mx', 'Español'),
        ]

        self.AUTH_PASSWORD_VALIDATORS = [
            {
                'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
            },
        ]

        # Security & X-Frame-Options Middleware
        self.SECURE_BROWSER_XSS_FILTER = self.env.bool('SECURE_BROWSER_XSS_FILTER', True)
        self.SECURE_CONTENT_TYPE_NOSNIFF = self.env.bool('SECURE_CONTENT_TYPE_NOSNIFF', True)
        self.X_FRAME_OPTIONS = self.env.str('X_FRAME_OPTIONS', 'DENY')

        self.CORS_ALLOW_HEADERS = (
            'x-requested-with',
            'content-type',
            'accept',
            'origin',
            'authorization',
            'x-csrftoken'
        )
        # phone number field

        # taggit

        self.ALLOWED_HOSTS = self.env.list('ALLOWED_HOSTS')
        self.INTERNAL_IPS = self.env.list('INTERNAL_IPS', default='127.0.0.1,')

        self.IGNORABLE_404_URLS = [
            re.compile(r'\.(php|cgi)$'),
            re.compile(r'^/phpmyadmin/'),
            re.compile(r'^/apple-touch-icon.*\.png$'),
            re.compile(r'^/favicon\.ico$'),
            re.compile(r'^/robots\.txt$'),
        ]

        self.LOGS_ROOT = self.BASE_DIR / '.logs'
        self.LOG_FORMAT = '|| %(levelname)s || %(asctime)s || %(module)s || %(name)s || %(lineno)s[%(process)d] || %(message)s'
        self.LOGGING = {
            'version': 1,
            'disable_existing_loggers': False,
            'formatters': {
                'default': {
                    'format': self.LOG_FORMAT,
                    'datefmt': '%d/%b/%Y %H:%M:%S',
                },
            },
            'filters': {
                'require_debug_true': {
                    '()': 'django.utils.log.RequireDebugTrue',
                },
                'require_debug_false': {
                    '()': 'django.utils.log.RequireDebugFalse',
                },
            },
            'handlers': {
                'console': {
                    'level': 'DEBUG',
                    'class': 'logging.StreamHandler',
                    'stream': 'ext://sys.stdout',
                    'formatter': 'default'
                },
                'errors': {
                    'level': 'ERROR',
                    'class': 'logging.StreamHandler',
                    'stream': 'ext://sys.stderr',
                    'formatter': 'default'
                },
                'null': {
                    'class': 'logging.NullHandler',
                },
            },
            'loggers': {
                '': {
                    'handlers': ['console', 'errors'],
                    'level': 'INFO',
                },
                'django': {
                    'handlers': ['console', 'errors'],
                    'level': self.env.str('LOG_DJANGO_LEVEL', "INFO"),
                    'propagate': False,
                },
                'BaseProject': {
                    'handlers': ['console', 'errors'],
                    'level': self.env.str('LOG_APP_LEVEL', "DEBUG"),
                    'propagate': False,
                },
                'django.security.DisallowedHost': {
                    'handlers': ['null'],
                    'propagate': False,
                },
            },
        }

    def _apply(self, component_cls, options: dict):
        config = component_cls(options).get_settings(self.env)
        for key, value in config.items():
            if key == "INSTALLED_APPS_EXTRA":
                self.INSTALLED_APPS += value
            else:
                setattr(self, key, value)

    @property
    def ADMINS(self):  # noqa
        admins_emails = self.env.str('ADMINS', '[[]]')
        return list(email for email in json.loads(admins_emails))

    @property
    def MANAGERS(self):  # noqa
        managers_emails = self.env.str('MANAGERS', '[[]]')
        return list(email for email in json.loads(managers_emails))

    @property
    def DATABASES(self):  # noqa
        _configuration = {}
        _caches = json.loads(self.env.str('DB_SETTINGS'))
        for _key in _caches.keys():
            _cache = _caches[_key]
            _configuration[_key] = {}
            _configuration[_key].update(self.env.db_url_config(_cache['url']))
        return _configuration

    @property
    def CACHES(self):  # noqa
        configuration = {}
        _caches = json.loads(self.env('CACHE_SETTINGS'))
        for _key in _caches.keys():
            _cache = _caches[_key]
            configuration[_key] = self.env.cache_url_config(url=_cache['url'])
            if _cache['engine'] == 'redis':
                configuration[_key].update({'BACKEND': 'django.core.cache.backends.redis.RedisCache'})
                if 'key_prefix' in _cache:
                    configuration[_key].update({'KEY_PREFIX': _cache['key_prefix']})
                if 'timeout' in _cache:
                    configuration[_key].update({'TIMEOUT': _cache['timeout']})
                if 'version' in _cache:
                    configuration[_key].update({'VERSION': _cache['version']})
                if 'options' in _cache:
                    configuration[_key].update({'OPTIONS': _cache['options']})
        return configuration

    @property
    def LOGIN_REDIRECT_URL(self): # noqa
        login_redirect_url = self.env("LOGIN_REDIRECT_URL")
        return login_redirect_url

    @classmethod
    def load_settings(cls, module_name):
        """
        Export class variables and properties to module namespace.
        This will export and class variable that is all upper case and doesn't
        begin with ``_``. These members will be set as attributes on the module
        ``module_name``.
        """
        self = cls()
        module = sys.modules[module_name]
        for (member, value) in inspect.getmembers(self):
            if member.isupper() and not member.startswith('_'):
                if isinstance(value, property):
                    value = value.fget(self)
                setattr(module, member, value)
